"""Database compatibility layer for StudyAI.

Production uses PostgreSQL when DATABASE_URL is configured.
Local development falls back to SQLite at DATABASE_PATH/studyai.db.
"""
from __future__ import annotations

import os
import sqlite3
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
DATABASE_URL_UNPOOLED = os.getenv("DATABASE_URL_UNPOOLED", "").strip()
DB_PATH = Path(os.getenv("DATABASE_PATH", BASE_DIR / "studyai.db"))

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # PostgreSQL is optional for local SQLite-only development until requirements are installed.
    psycopg = None
    dict_row = None


def is_postgres() -> bool:
    return bool(DATABASE_URL)


def backend_name() -> str:
    return "postgresql" if is_postgres() else "sqlite"


if psycopg is not None:
    INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.IntegrityError)
    DATABASE_ERRORS = (sqlite3.Error, psycopg.Error)
else:
    INTEGRITY_ERRORS = (sqlite3.IntegrityError,)
    DATABASE_ERRORS = (sqlite3.Error,)


def _postgres_sql(sql: str) -> str:
    # StudyAI SQL does not contain literal question marks. Keeping qmark-style SQL
    # in the application lets the same statements run against sqlite3 and Psycopg.
    return sql.replace("?", "%s")


class DatabaseConnection:
    def __init__(self):
        self.postgres = is_postgres()
        if self.postgres:
            if psycopg is None:
                raise RuntimeError(
                    "DATABASE_URL is configured but Psycopg is not installed. "
                    "Run pip install -r requirements.txt."
                )
            connect_kwargs = {
                "row_factory": dict_row,
                "connect_timeout": 10,
                "application_name": "studyai",
            }
            # Neon pooled endpoints use PgBouncer transaction pooling. Disable
            # automatic server-side prepared statements for maximum compatibility.
            if "-pooler." in DATABASE_URL:
                connect_kwargs["prepare_threshold"] = None
            self.raw = psycopg.connect(DATABASE_URL, **connect_kwargs)
        else:
            self.raw = sqlite3.connect(DB_PATH)
            self.raw.row_factory = sqlite3.Row
            self.raw.execute("PRAGMA foreign_keys = ON")

    def execute(self, sql: str, params=()):
        if self.postgres:
            sql = _postgres_sql(sql)
        return self.raw.execute(sql, params)

    def __enter__(self):
        self.raw.__enter__()
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            return self.raw.__exit__(exc_type, exc, tb)
        finally:
            try:
                self.raw.close()
            except Exception:
                pass

    def close(self):
        self.raw.close()


def db() -> DatabaseConnection:
    return DatabaseConnection()


SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE COLLATE NOCASE,
    name TEXT NOT NULL DEFAULT '',
    password_hash TEXT,
    created_at INTEGER NOT NULL,
    last_login INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS oauth_identities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    provider TEXT NOT NULL,
    provider_sub TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    UNIQUE(provider, provider_sub),
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_state (
    user_id INTEGER PRIMARY KEY,
    state_json TEXT NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS question_reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    source TEXT NOT NULL,
    question_ref TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL,
    details TEXT NOT NULL DEFAULT '',
    question_text TEXT NOT NULL,
    passage TEXT NOT NULL DEFAULT '',
    context TEXT NOT NULL DEFAULT '',
    page TEXT NOT NULL DEFAULT '',
    created_at INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS client_errors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    message TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT '',
    line INTEGER NOT NULL DEFAULT 0,
    column_no INTEGER NOT NULL DEFAULT 0,
    page TEXT NOT NULL DEFAULT '',
    created_at INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_oauth_identities_user_id ON oauth_identities(user_id);
CREATE INDEX IF NOT EXISTS idx_question_reports_user_id ON question_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_client_errors_user_id ON client_errors(user_id);
"""

POSTGRES_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL DEFAULT '',
        password_hash TEXT,
        created_at BIGINT NOT NULL,
        last_login BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS oauth_identities (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        provider TEXT NOT NULL,
        provider_sub TEXT NOT NULL,
        created_at BIGINT NOT NULL,
        UNIQUE(provider, provider_sub)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_state (
        user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        state_json TEXT NOT NULL,
        updated_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS question_reports (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        source TEXT NOT NULL,
        question_ref TEXT NOT NULL DEFAULT '',
        category TEXT NOT NULL,
        details TEXT NOT NULL DEFAULT '',
        question_text TEXT NOT NULL,
        passage TEXT NOT NULL DEFAULT '',
        context TEXT NOT NULL DEFAULT '',
        page TEXT NOT NULL DEFAULT '',
        created_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS client_errors (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        message TEXT NOT NULL,
        source TEXT NOT NULL DEFAULT '',
        line BIGINT NOT NULL DEFAULT 0,
        column_no BIGINT NOT NULL DEFAULT 0,
        page TEXT NOT NULL DEFAULT '',
        created_at BIGINT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_oauth_identities_user_id ON oauth_identities(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_question_reports_user_id ON question_reports(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_client_errors_user_id ON client_errors(user_id)",
]


def init_db() -> None:
    if is_postgres():
        with db() as conn:
            for statement in POSTGRES_SCHEMA:
                conn.execute(statement)
        return

    conn = sqlite3.connect(DB_PATH)
    try:
        conn.execute("PRAGMA foreign_keys = ON")
        conn.executescript(SQLITE_SCHEMA)
        conn.commit()
    finally:
        conn.close()


def insert_and_get_id(conn: DatabaseConnection, sql: str, params=()) -> int:
    if conn.postgres:
        row = conn.execute(sql.rstrip().rstrip(";") + " RETURNING id", params).fetchone()
        return int(row["id"])
    cursor = conn.execute(sql, params)
    return int(cursor.lastrowid)
